CREATE TABLE analytics.user_monthly_property (
    CCOD VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    unique_work_types INTEGER,
    cancelled_work INTEGER,
    cancellation_rate REAL,
    confirmation_rate REAL,
    avg_services_per_work REAL,
    work_last_30d INTEGER,
    confirmed_30d INTEGER,
    cancelled_30d INTEGER,
    services_30d INTEGER,
    work_types_30d INTEGER,
    cancellation_rate_30d REAL,
    confirmation_rate_30d REAL,
    work_last_60d INTEGER,
    confirmed_60d INTEGER,
    cancelled_60d INTEGER,
    services_60d INTEGER,
    work_types_60d INTEGER,
    cancellation_rate_60d REAL,
    confirmation_rate_60d REAL,
    work_last_90d INTEGER,
    confirmed_90d INTEGER,
    cancelled_90d INTEGER,
    services_90d INTEGER,
    work_types_90d INTEGER,
    cancellation_rate_90d REAL,
    confirmation_rate_90d REAL,
    avg_csi_score REAL,
    csi_score_30d REAL,
    csi_score_60d REAL,
    csi_score_90d REAL,
    csi_survey_count INTEGER,
    csi_survey_count_30d INTEGER,
    csi_survey_count_60d INTEGER,
    csi_survey_count_90d INTEGER,
    num_interactions INTEGER,
    voc_count INTEGER,
    non_voc_count INTEGER,
    voc_ratio REAL,
    interactions_30d INTEGER,
    voc_30d INTEGER,
    non_voc_30d INTEGER,
    voc_ratio_30d REAL,
    interactions_60d INTEGER,
    voc_60d INTEGER,
    non_voc_60d INTEGER,
    voc_ratio_60d REAL,
    interactions_90d INTEGER,
    voc_90d INTEGER,
    non_voc_90d INTEGER,
    voc_ratio_90d REAL,
    recent_90d_activity_ratio REAL,
    recent_30d_activity_ratio REAL,
    activity_density REAL,
    confirmation_rate_change REAL,
    cancellation_rate_change REAL,
    voc_to_work_ratio REAL,
    recent_30d_to_90d_ratio REAL,
    PRIMARY KEY ("CCOD", created_at)
) PARTITION BY RANGE (created_at);

COMMENT ON TABLE analytics.user_monthly_property IS 'Stores calculated features for each user at a specific point in time.';
COMMENT ON COLUMN analytics.user_monthly_property."CCOD" IS 'Customer code';
COMMENT ON COLUMN analytics.user_monthly_property.created_at IS 'Timestamp when the features were generated';
